Use list command and allow spaces in names
joshdk/ykmango pull request #10
Opened 2018-08-08 12:30 UTC by SamClinckspoor

ykman has a list command to list available OATH slots. OATH slot
names can also have spaces in the name.

2018-08-19 19:24 UTC, joshdk requested changes
Thanks for the PR @SamClinckspoor!

I left some comments on the diff. Your PR actually [obsoletes some test cases](https://github.com/joshdk/ykmango/blob/master/list_test.go#L47-L71), since `ymkan oath list` has a simpler output format.

I've reconfigured CircleCI on the repo to build forked PRs, so if you push more commits, it should trigger a build.

You can also run `go test -v ./...` locally.

Cheers!

2018-08-19 19:24 UTC, joshdk commented on list.go
> +	cmd := exec.Command("ykman", "oath", "list")
I like the idea of using `ykman oath list` internally, not sure why I didn't do that in the first place...

2018-08-19 19:24 UTC, joshdk commented on list.go
> +		chunks := strings.Split(line, "\n")
This split will never actually end up splitting anything, as [`process()` already splits on newlines](https://github.com/joshdk/ykmango/blob/master/utils.go#L15-L16).

Assuming that `ykman oath list` prints just the slot names (and nothing more), we can actually return the lines verbatim, after checking for errors. A (now much more) reduced function body can now look like:

```go
func parseList(body string, err error) ([]string, error) {
	lines := process(body)

	if err != nil {
		...snip
	}

	return lines, nil
}
```

2018-08-21 08:49 UTC, SamClinckspoor commented
Thank you for the pointers @joshdk 
I pushed some fixes and additional tests.

2018-08-21 15:48 UTC, joshdk approved these changes

2018-08-21 15:48 UTC, merged

2018-08-21 15:49 UTC, joshdk commented
Merged! Thank you @SamClinckspoor for the improvements!